### ISSUE TITLE
Emerging Technologies Dashboard: Understand Data Gap

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-metrics-org#130]
There was a data gap between approx end of November 2016 to beginning of May 2017 for both. What was the reason for it?

**Comment by dicortazar** [comment]
After checking the dashboard I can not reproduce the issue. I do not see any low activity. I need extra information with this respect as requested by email:
* Please double check that this is still taking place and if so, double check if there are any filters/stickers applied in the dashboard.
* If you reproduce the issue again, please send a short link + a screenshot of the full Kibana dashboard including the timeframe selection and the filters on the top.

Thanks!

**Comment by hmitsch** [comment]
---------- Forwarded message ----------
From: Henrik Mitsch <hmitsch@mozilla.com>
Date: Sun, Sep 3, 2017 at 2:49 PM
Subject: Fwd: ET Dashboard
To: Luis Cañas <lcanas@bitergia.com>, support <support@bitergia.com>
Cc: Hermina Condei <hcondei@mozilla.com>


Dear Bitergia Support,
Hi Luis,

Hermina had an interesting observation on Friday. Can you please read her
mail below and help us verify if the gaps between November and May are a
bug?


Regards,
  Henrik


---------- Forwarded message ---------
From: Hermina <hcondei@mozilla.com>
Date: Fri 1. Sep 2017 at 20:48
Subject: ET Dashboard
To: Henrik Mitsch <hmitsch@mozilla.com>

...

He had a question as he was surprised to see that when selecting either
Rust or A-frame, there is a gap at the level of submitted issues and pull
requests between approx end of November to beginning of May for both. I've
attached screenshots so that you see what I mean. The timeline chosen was
Last 1 year. He doesn't understand why that gap for both projects as he
doesn't think it's normal and asked me if I could first check with Bitergia
to have a confirmation that the numbers are indeed correct so that if they
are, he could start asking his teams.

when I don't filter and look at the two projects together, there is no gap
for the same period (3rd screenshot)...

Could you please check as well and let me know what you think? Also, if you
will also notice the problem, do you have anyone at Bitergia you could
forward this request now?



A-frame

[image: Inline image 1]

Rust

[image: Inline image 2]

Both Rust and A-frame

[image: Inline image 3]

**Comment by hmitsch** [comment]
---------- Forwarded message ----------
From: Luis Cañas-Díaz <lcanas@bitergia.com>
Date: Wed, Sep 13, 2017 at 3:57 PM
Subject: Re: ET Dashboard
To: Henrik Mitsch <hmitsch@mozilla.com>, support <support@bitergia.com>
Cc: Hermina Condei <hcondei@mozilla.com>


On 13/09/17 15:43, Henrik Mitsch wrote:
> Hi Bitergia Support Team,
>
> any update on this?

Dear Hermina and Henrik,
data was collected again earlier this week. The gap is gone

https://analytics.mozilla.community:443/goto/5a03461860d1bceba0ef6885e58c75
bc

Best,
Luis.

**Comment by hmitsch** [comment]
Hi @dicortazar 

>    Please double check that this is still taking place and if so, double check if there are any filters/stickers applied in the dashboard.

No, the issue is gone. It was fixed by renewed data collection a week ago.

We are now asking what was the root cause of that data inconsistency. The reason we ask is because we are in a trust building phase and want to be able to explain our glitches.

Best regards,
   Henrik

**Comment by jgbarah** [comment]
Mmmm. I will try to contact @sanacl who is in parent leave these days. But it is likely that the problem was related to a bug in how we update data from git repos with certain versions of Perceval. Maybe you remember that we had a similar problem with some repos duiring the analysis we did back in May. We thought it was fixed, but it seems in some cases it wasn't. The pattern is similar to the one described (a gap in data after the initial retrieval). However, I will check with @sanacl. And in any case, it is likely that we will re-retrieve all the data for all the repos, for being on the safe side.

If it was some other problem, I will let you know as well.

**Comment by jgbarah** [comment]
First, I read more carefully the full original message by Hermina. I noticed the gap was in GitHub, so nothing to do with the git data I mentioned, sorry about the noise.

I also located our internal ticket about the issue, and I see @sanacl recreated the GitHub index from scratch. I still don't know why he did that. But that's the reason there is no gap anymore.

**Comment by hmitsch** [comment]
We decide to close this.
